### ISSUE TITLE
First Issue

### ISSUE THREAD

**Issue by pamearteaga** [pamearteaga/cardify#1]
Detectamos que podríamos tener dificultades con lograr que el plugin reconozca las etiquetas `<img>` automáticamente y, adicionalmente que envuelva esta etiqueta y la intercambie por la etiqueta `<figure>` he inserte el `<figcaption>` con el texto del atributo `alt`.

**Comment by Jocelyn1912** [comment]
Logrado!

**Comment by Jocelyn1912** [comment]
Estamos listas con esto, hay que cerrar el issue.
